---
name: Epiphany embedded browser
version: 1.0.1
slug: embdbrowser
description: Epiphany embedded browser
url: https://github.com/bigmoby/addon-embedded-browser/tree/main/embedded_browser
arch:
  - amd64
  - aarch64
apparmor: false
host_network: false
stage: stable
init: false
hassio_api: true
privileged:
  - NET_ADMIN
udev: false
usb: false
startup: services
ingress: true
ingress_entry: ingress.html
ingress_port: 8099
kernel_modules: false
image: "bigmoby/{arch}-addon-embedded-browser"
options:
  start_url: "http://192.168.1.1"
  vnc_password: ""
schema:
  start_url: url
  vnc_password: password?
